auto_project:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: auto-project-493707
      dataset: staging
      keyfile: /opt/airflow/gcp-credentials.json
      location: asia-southeast2
      timeout_seconds: 300
      threads: 4