services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-webserver:
    build: .
    user: "0:0"
    command: webserver
    ports:
      - "8080:8080"
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: 'Asia/Jakarta'
      AIRFLOW__WEBSERVER__SECRET_KEY: '${AIRFLOW_SECRET_KEY}'
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/gcp-credentials.json
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
      - ./data:/opt/airflow/data
      - ./ingestion:/opt/airflow/ingestion
      - ./gcp-credentials.json:/opt/airflow/gcp-credentials.json:ro
    depends_on:
      postgres:
        condition: service_healthy

  airflow-scheduler:
    build: .
    user: "0:0"
    command: scheduler
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: 'Asia/Jakarta'
      AIRFLOW__WEBSERVER__SECRET_KEY: '${AIRFLOW_SECRET_KEY}'
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/gcp-credentials.json
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
      - ./data:/opt/airflow/data
      - ./ingestion:/opt/airflow/ingestion
      - ./gcp-credentials.json:/opt/airflow/gcp-credentials.json:ro
    depends_on:
      postgres:
        condition: service_healthy

  airflow-init:
    build: .
    user: "0:0"
    command: version
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: 'Asia/Jakarta'
      AIRFLOW__WEBSERVER__SECRET_KEY: '${AIRFLOW_SECRET_KEY}'
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/gcp-credentials.json
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
      - ./data:/opt/airflow/data
      - ./ingestion:/opt/airflow/ingestion
      - ./gcp-credentials.json:/opt/airflow/gcp-credentials.json:ro
    depends_on:
      postgres:
        condition: service_healthy

  dbt-docs:
    image: python:3.11-slim
    command: python -m http.server 8081 --directory /docs
    volumes:
      - ./dbt/nhtsa_project/target:/docs
    ports:
      - "8081:8081"
    restart: always

volumes:
  postgres_db_volume: